ci: add clang-tidy to static analysis workflow.
The check for GITHUB_HEAD_REF is used so the same workflow works for PRs
and for branches.

The issue causing git-config(1) to be necessary is tracked in [1].

Meson supports a clang-tidy target of its own, but it's not really
usable for our purposes [2].

[1] https://github.com/actions/checkout/issues/1169
[2] https://github.com/mesonbuild/meson/issues/2383

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -19,6 +19,19 @@ jobs:
       fail-fast: false
       matrix:
         tool:
+          # clang-tidy is more extensive and the list of checks isn't final, so fixing all of them at once isn't tractable;
+          # therefore, the job doesn't fail due to clang-tidy, it's simply informative
+          - packages: "clang-tidy"
+            command: "clang-tidy '--warnings-as-errors=-*' -p build/ $(git ls-files | grep '\\.c\\+$')"
+          # however, we should check that the changed lines of code don't have any tidy warnings
+          - packages: "clang-tidy"
+            command: |
+              if [ -n \"$GITHUB_BASE_REF\" ]; then
+                git diff -U0 origin/$GITHUB_BASE_REF > diff
+                clang-tidy-diff -p1 -config-file .clang-tidy -path build/ < diff > result && exitcode=0 || exitcode=$?
+                cat result
+                exit $exitcode
+              fi
           # cppcheck doesn't check as much, so we can make the job fail because of it;
           # tests are skipped due to issues with Catch2 headers
           - packages: "cppcheck"
